[package]
name = "qr-code-encoder"
version = "0.1.0"

[dependencies]
wasm-bindgen = "0.2.92"
image = "0.25.1"
qrcode = "0.14.0"
serde = "1.0.203"
serde_json = "1.0.117"
base64 = "0.22.1"

[lib]
crate-type = ["cdylib"]
